# Partition module configuration linking to kpmcore
---
efiSystemPartition:     "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
initialPartitioningChoice: none
initialSwapChoice:         none
defaultFileSystemType:     "ext4"
