# Calamares main configuration file for ArchBox Linux
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id:       clean
    module:   unpackfs
    config:   unpackfs.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs@clean
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - bootloader
  - show:
    - finished

branding: archbox
prompt-install: true
dont-chroot: false

