# Users configuration file
---
defaultGroups:
    - lp
    - wheel
    - physical
    - sys
    - audio
    - input
    - video
    - storage
    - power
    - network
autologinGroup:  autologin
mandatoryUserGroups: [ wheel ]
initialPasswordToDisplay: ""
