# Welcome module configuration
---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
requirements:
    requiredRam:        2.0
    requiredDiskSpace:  8.0
    internetCheckUrl:   http://google.com
    check:
        - power
        - storage
        - ram
    required:
        - storage
        - ram
